### ISSUE TITLE
Parameter Confusion

### ISSUE THREAD

**Issue by curtissladebp** [javiersoriano/sentinelascode#10]
https://github.com/javiersoriano/sentinelascode/blob/201b7f11a81aa123a2edbaa3b27b8bca9c88b20e/Scripts/CreateWorkbooks.ps1#L5

This parameter should be labelled from Workspace to WorkspaceName or similar.
I spent more hours than i care to confirm trying to troubleshoot why this wasn't working, when I even got a Succeeded msg.
I was using the workspace ID and not the Name.
If you use the workspaceId vs the name, it goes 'somewhere' in the subscription (but i couldn't figure out where) :)
Please rename for clarification in the future, thanks.

**Comment by javiersoriano** [comment]
Hi @curtissladebp , this repository is no longer maintained. For the latest way to manage Sentinel content as code, use Sentinel Repositories: https://docs.microsoft.com/en-us/azure/sentinel/ci-cd?tabs=github
