### ISSUE TITLE
CreateWorkbooks.ps1 file uses invalid parameter

### ISSUE THREAD

**Issue by rskalitzky** [javiersoriano/sentinelascode#3]
Within the CreateWorkbooks.ps1 file "New-AzResourceGroupDeployment" contains a parameter of WorkbookSourceId.  THis cmdlet does contain that parameter.

**Comment by javiersoriano** [comment]
The New-AzResourceGroupDeployment cmdlet accepts passing parameters to the template to be deployed with the parameter name and value as done in CreateWorkbooks.ps1 script. You can just run the command as is from any PS command line and it will succeed.

**Comment by rskalitzky** [comment]
My point was the You cannot pass the “-workspacesourceid” to the “new-azresourcegroupdeployment” cmdlet (used in the script) when the cmdlet does not accept that parameter. (See image below - there is no workspacesourceid parameter).   that do
