### ISSUE TITLE
Unable to pass new entityMappings

### ISSUE THREAD

**Issue by acastellano454** [javiersoriano/sentinelascode#8]
We've been unsuccessful passing entityMappings through the DevOps pipeline.  We've tried a couple of different JSON payloads, even one based on the JSON structure of an existing rule with manually-applied entityMappings (see attached screenshot).  This could be a syntax issue, but we wanted to double-check also if new entities aren't supported for passing through the pipeline to begin with?

![entity_json](https://user-images.githubusercontent.com/70961202/157685408-baeea5d3-3f9f-4f20-9d36-fd8c89ac6fa4.PNG)

**Comment by javiersoriano** [comment]
HI @acastellano454 , this repo is no longer maintained. The recommended way to do Sentinel as code is now Respositories, which uses ARM templates: https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/enable-continuous-deployment-natively-with-microsoft-sentinel/ba-p/2929413 

Regards
